app:
  name: "grdudation_design"
  port: :5555
mysql:
  host: "127.0.0.1"
  user: "root"
  password: "123456"
  db_name: "appDB"
  port: 3306
  max_idle_conns: 11
  max_open_conns: 114
  dsn: "root:123456@tcp(127.0.0.1:3306)/appDB?charset=utf8mb4&parseTime=True&loc=Local"
logger:
  level: "info"
  max_size: 500
  max_age: 180
  max_backups: 7
