import { createApp } from "vue";
import App from "./App.vue";
import router from "@/router/index";
import "@/assets/style/global.css";
import ElementPlus from "element-plus";
import "element-plus/dist/index.css";
const vueInstance = createApp(App);
vueInstance.use(ElementPlus);
vueInstance.use(router);
vueInstance.mount("#app");
