DROP TABLE IF EXISTS users;

CREATE TABLE
    `users` (
        `user_id` int (11) unsigned NOT NULL AUTO_INCREMENT COMMENT '用户ID',
        `user_name` varchar(20) NOT NULL COMMENT '用户名',
        `email` varchar(320) COMMENT '邮箱',
        `phone_number` varchar(11) DEFAULT NULL COMMENT '手机号',
        `password` varchar(255) NOT NULL COMMENT '密码',
        `confirm_password` varchar(255) NOT NULL COMMENT '重复密码',
        `gender` tinyint (2) NOT NULL DEFAULT '0' COMMENT '性别 0:未知 1:男 2:女',
        `is_email_verified` tinyint (1) NOT NULL DEFAULT '0' COMMENT '邮箱是否已验证',
        `is_phone_verified` tinyint (1) NOT NULL DEFAULT '0' COMMENT '手机号是否已验证',
        `third_party_accounts` json DEFAULT NULL COMMENT '第三方账号信息',
        `avatar` varchar(255) DEFAULT NULL COMMENT '头像token',
        `cover` varchar(50) DEFAULT NULL COMMENT '封面图片token',
        `follower_count` int (11) unsigned NOT NULL DEFAULT '0' COMMENT '关注我的人数',
        `followee_count` int (11) unsigned NOT NULL DEFAULT '0' COMMENT '我关注的人数',
        `following_article_count` int (11) unsigned NOT NULL DEFAULT '0' COMMENT '我关注的文章数',
        `following_question_count` int (11) unsigned NOT NULL DEFAULT '0' COMMENT '我关注的问题数',
        `following_topic_count` int (11) unsigned NOT NULL DEFAULT '0' COMMENT '我关注的话题数',
        `article_count` int (11) unsigned NOT NULL DEFAULT '0' COMMENT '我发表的文章数量',
        `question_count` int (11) unsigned NOT NULL DEFAULT '0' COMMENT '我发表的问题数量',
        `answer_count` int (11) unsigned NOT NULL DEFAULT '0' COMMENT '我发表的回答数量',
        `notification_unread` int (11) unsigned NOT NULL DEFAULT '0' COMMENT '未读通知数',
        `inbox_unread` int (11) unsigned NOT NULL DEFAULT '0' COMMENT '未读私信数',
        `headline` varchar(40) DEFAULT NULL COMMENT '一句话介绍',
        `bio` varchar(160) DEFAULT NULL COMMENT '个人简介',
        `company` varchar(255) DEFAULT NULL COMMENT '公司名称',
        `location` varchar(255) DEFAULT NULL COMMENT '地址',
        `created_at` int (10) unsigned NOT NULL DEFAULT '0' COMMENT '注册时间',
        `updated_at` int (10) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
        `deleted_at` int (10) unsigned NOT NULL DEFAULT '0' COMMENT '禁用时间',
        PRIMARY KEY (`user_id`),
        KEY `user_name` (`user_name`),
        KEY `email` (`email`),
        KEY `created_at` (`created_at`)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '用户表';