// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file message.proto (package protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message as Message$1 } from "@bufbuild/protobuf";

/**
 * Describes the file message.proto.
 */
export const file_message: GenFile = /*@__PURE__*/
  fileDesc("Cg1tZXNzYWdlLnByb3RvEghwcm90b2NvbCLBAQoHTWVzc2FnZRIOCgZhdmF0YXIYASABKAkSFAoMZnJvbVVzZXJuYW1lGAIgASgJEgwKBGZyb20YAyABKAkSCgoCdG8YBCABKAkSDwoHY29udGVudBgFIAEoCRITCgtjb250ZW50VHlwZRgGIAEoBRIMCgR0eXBlGAcgASgJEhMKC21lc3NhZ2VUeXBlGAggASgFEgsKA3VybBgJIAEoCRISCgpmaWxlU3VmZml4GAogASgJEgwKBGZpbGUYCyABKAxiBnByb3RvMw");

/**
 * @generated from message protocol.Message
 */
export type Message = Message$1<"protocol.Message"> & {
  /**
   * @generated from field: string avatar = 1;
   */
  avatar: string;

  /**
   * @generated from field: string fromUsername = 2;
   */
  fromUsername: string;

  /**
   * @generated from field: string from = 3;
   */
  from: string;

  /**
   * @generated from field: string to = 4;
   */
  to: string;

  /**
   * @generated from field: string content = 5;
   */
  content: string;

  /**
   * @generated from field: int32 contentType = 6;
   */
  contentType: number;

  /**
   * @generated from field: string type = 7;
   */
  type: string;

  /**
   * @generated from field: int32 messageType = 8;
   */
  messageType: number;

  /**
   * @generated from field: string url = 9;
   */
  url: string;

  /**
   * @generated from field: string fileSuffix = 10;
   */
  fileSuffix: string;

  /**
   * @generated from field: bytes file = 11;
   */
  file: Uint8Array;
};

/**
 * Describes the message protocol.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema: GenMessage<Message> = /*@__PURE__*/
  messageDesc(file_message, 0);

